=== alumnoangel/examenLenguaje/ExamenPedidos/pedidos.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT pedido (sucursales)*>
<!ELEMENT sucursales (direcciones+,nombreTrabajador,fechaPedido,observacionesPedido?,articulo+)>
<!ATTLIST sucursales codPedido CDATA #REQUIRED>
<!ELEMENT direcciones (#PCDATA)>
<!ELEMENT nombreTrabajador (#PCDATA)>
<!ELEMENT fechaPedido (#PCDATA)>
<!ELEMENT observacionesPedido (#PCDATA)>
<!ELEMENT articulo (unidadesPedidas+, precioUnidad, observacionesArt, revision)>
<!ATTLIST articulo codArticulo CDATA #REQUIRED>
<!ELEMENT unidadesPedidas (#PCDATA)>
<!ELEMENT precioUnidad (#PCDATA)>
<!ELEMENT observacionesArt (#PCDATA)>
<!ELEMENT revision (#PCDATA)>

=== alumnoangel/examenLenguaje/ExamenPedidos/pedidos_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE pedido SYSTEM "pedidos.dtd">

<pedido>
    <sucursales codPedido="P9852145">
        <direcciones>calle falsa 123</direcciones>
        <nombreTrabajador>Mariano Rajoy</nombreTrabajador>
        <fechaPedido>12-06-2020</fechaPedido>
        <observacionesPedido>urgente</observacionesPedido>
        <articulo codArticulo="ODN-597">
            <unidadesPedidas>3</unidadesPedidas>
            <precioUnidad>7</precioUnidad>
            <observacionesArt>fragil</observacionesArt>
            <revision>4</revision>
        </articulo>
    </sucursales>
</pedido>
